REM needs GR01.HES, ... and GR01.HED, ...
copy gr01.hes gr.hes
copy gr01.hea gr.hea
elemse.exe
copy elemse.dat elemse01.dat

copy gr02.hes gr.hes
copy gr02.hea gr.hea
elemse.exe
copy elemse.dat elemse02.dat

copy gr03.hes gr.hes
copy gr03.hea gr.hea
elemse.exe
copy elemse.dat elemse03.dat

copy gr04.hes gr.hes
copy gr04.hea gr.hea
elemse.exe
copy elemse.dat elemse04.dat

copy gr05.hes gr.hes
copy gr05.hea gr.hea
elemse.exe
copy elemse.dat elemse05.dat

copy gr06.hes gr.hes
copy gr06.hea gr.hea
elemse.exe
copy elemse.dat elemse06.dat

copy gr07.hes gr.hes
copy gr07.hea gr.hea
elemse.exe
copy elemse.dat elemse07.dat

copy gr08.hes gr.hes
copy gr08.hea gr.hea
elemse.exe
copy elemse.dat elemse08.dat

copy gr09.hes gr.hes
copy gr09.hea gr.hea
elemse.exe
copy elemse.dat elemse09.dat

copy gr10.hes gr.hes
copy gr10.hea gr.hea
elemse.exe
copy elemse.dat elemse10.dat

copy gr11.hes gr.hes
copy gr11.hea gr.hea
elemse.exe
copy elemse.dat elemse11.dat

copy gr12.hes gr.hes
copy gr12.hea gr.hea
elemse.exe
copy elemse.dat elemse12.dat

copy gr13.hes gr.hes
copy gr13.hea gr.hea
elemse.exe
copy elemse.dat elemse13.dat

copy gr14.hes gr.hes
copy gr14.hea gr.hea
elemse.exe
copy elemse.dat elemse14.dat

copy gr15.hes gr.hes
copy gr15.hea gr.hea
elemse.exe
copy elemse.dat elemse15.dat



copy gr16.hes gr.hes
copy gr16.hea gr.hea
elemse.exe
copy elemse.dat elemse16.dat

copy gr17.hes gr.hes
copy gr17.hea gr.hea
elemse.exe
copy elemse.dat elemse17.dat

copy gr18.hes gr.hes
copy gr18.hea gr.hea
elemse.exe
copy elemse.dat elemse18.dat

copy gr19.hes gr.hes
copy gr19.hea gr.hea
elemse.exe
copy elemse.dat elemse19.dat

copy gr20.hes gr.hes
copy gr20.hea gr.hea
elemse.exe
copy elemse.dat elemse20.dat

copy gr21.hes gr.hes
copy gr21.hea gr.hea
elemse.exe
copy elemse.dat elemse21.dat

copy gr22.hes gr.hes
copy gr22.hea gr.hea
elemse.exe
copy elemse.dat elemse22.dat

copy gr23.hes gr.hes
copy gr23.hea gr.hea
elemse.exe
copy elemse.dat elemse23.dat

copy gr24.hes gr.hes
copy gr24.hea gr.hea
elemse.exe
copy elemse.dat elemse24.dat

copy gr25.hes gr.hes
copy gr25.hea gr.hea
elemse.exe
copy elemse.dat elemse25.dat

REM creates ELEMSE01.DAT, ...

del gr.hea
del gr.hes
del elemse.dat
